#spring.datasource.url=jdbc:mysql://localhost/test spring.datasource.username=dbuser spring.datasource.password=dbpass ...
#spring:
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:test
  spring.thymeleaf.cache: false
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
spring:
  h2:
    console:
      enabled: true
#spring.jpa.properties.hibernate.use_sql_comments: true
#spring.jpa.properties.hibernate.type: trace

#spring.jpa.properties.hibernate.show_sql: true
#spring.jpa.properties.hibernate.format_sql: true
logging:
  level:
    com.demo.spring_security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE